/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiMeshProfileRouteImport } from './routes/api/mesh-profile'
import { Route as ApiMeshStorageRouteImport } from './routes/api/mesh-storage'
import { Route as ApiMeshUploadRouteImport } from './routes/api/mesh-upload'
import { Route as ApiProviderKeysRouteImport } from './routes/api/provider-keys'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshProfileRoute = ApiMeshProfileRouteImport.update({
  id: '/api/mesh-profile',
  path: '/api/mesh-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshStorageRoute = ApiMeshStorageRouteImport.update({
  id: '/api/mesh-storage',
  path: '/api/mesh-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshUploadRoute = ApiMeshUploadRouteImport.update({
  id: '/api/mesh-upload',
  path: '/api/mesh-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderKeysRoute = ApiProviderKeysRouteImport.update({
  id: '/api/provider-keys',
  path: '/api/provider-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/mesh-profile': typeof ApiMeshProfileRoute
  '/api/mesh-storage': typeof ApiMeshStorageRoute
  '/api/mesh-upload': typeof ApiMeshUploadRoute
  '/api/provider-keys': typeof ApiProviderKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/mesh-profile': typeof ApiMeshProfileRoute
  '/api/mesh-storage': typeof ApiMeshStorageRoute
  '/api/mesh-upload': typeof ApiMeshUploadRoute
  '/api/provider-keys': typeof ApiProviderKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/mesh-profile': typeof ApiMeshProfileRoute
  '/api/mesh-storage': typeof ApiMeshStorageRoute
  '/api/mesh-upload': typeof ApiMeshUploadRoute
  '/api/provider-keys': typeof ApiProviderKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/chat'
    | '/api/mesh-profile'
    | '/api/mesh-storage'
    | '/api/mesh-upload'
    | '/api/provider-keys'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/chat'
    | '/api/mesh-profile'
    | '/api/mesh-storage'
    | '/api/mesh-upload'
    | '/api/provider-keys'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/chat'
    | '/api/mesh-profile'
    | '/api/mesh-storage'
    | '/api/mesh-upload'
    | '/api/provider-keys'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMeshProfileRoute: typeof ApiMeshProfileRoute
  ApiMeshStorageRoute: typeof ApiMeshStorageRoute
  ApiMeshUploadRoute: typeof ApiMeshUploadRoute
  ApiProviderKeysRoute: typeof ApiProviderKeysRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh-profile': {
      id: '/api/mesh-profile'
      path: '/api/mesh-profile'
      fullPath: '/api/mesh-profile'
      preLoaderRoute: typeof ApiMeshProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh-storage': {
      id: '/api/mesh-storage'
      path: '/api/mesh-storage'
      fullPath: '/api/mesh-storage'
      preLoaderRoute: typeof ApiMeshStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh-upload': {
      id: '/api/mesh-upload'
      path: '/api/mesh-upload'
      fullPath: '/api/mesh-upload'
      preLoaderRoute: typeof ApiMeshUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-keys': {
      id: '/api/provider-keys'
      path: '/api/provider-keys'
      fullPath: '/api/provider-keys'
      preLoaderRoute: typeof ApiProviderKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMeshProfileRoute: ApiMeshProfileRoute,
  ApiMeshStorageRoute: ApiMeshStorageRoute,
  ApiMeshUploadRoute: ApiMeshUploadRoute,
  ApiProviderKeysRoute: ApiProviderKeysRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
